### ISSUE TITLE
Next Version To-do list

### ISSUE THREAD

**Issue by CyaanKnight** [CyaanKnight/BattleMod_ReDux#1]
For now -
- [ ] Backport v10's hitstun
- [ ] Merge Corpses, Hitfeed and Guard Frames
- [ ] Merge the tumblestunbreak build

For Later
- [ ] Make Arena ( and possibly) Survival more engaging
- [ ] Add New gamemodes
- [ ] Rework/Rebalance Characters
- [ ] Revamp and Make new maps for vanilla
